from alembic import op

revision = "5f035fd6bb15"
down_revision = "9d8057e06970"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "billing", "user", ["user_id"], ["id"], ondelete="CASCADE", use_alter=True
    )
    op.create_foreign_key(
        None,
        "shipping",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
        use_alter=True,
    )
    op.drop_constraint("user_billing_id_fkey", "user", type_="foreignkey")
    op.drop_constraint("user_shipping_id_fkey", "user", type_="foreignkey")
    op.create_foreign_key(
        None, "user", "shipping", ["shipping_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "user", "billing", ["billing_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###
