import sqlalchemy as sa
from alembic import op

revision = "6113080382c6"
down_revision = "837613a461bb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "coupon",
        "code",
        existing_type=sa.VARCHAR(length=16),
        type_=sa.String(length=32),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
