import sqlalchemy as sa
from alembic import op

revision = "40fd00f351db"
down_revision = "6113080382c6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order",
        "coupon_code",
        existing_type=sa.VARCHAR(length=16),
        type_=sa.String(length=32),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
