import sqlalchemy as sa
from alembic import op

revision = "d8b8fcd93025"
down_revision = "7c23948d375e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("setting", sa.Column("cached_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###
