import sqlalchemy as sa
from alembic import op

revision = "4b17d67bafc1"
down_revision = "bc5de40a50f4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("billing", sa.Column("state", sa.String(length=64), nullable=True))
    op.add_column("shipping", sa.Column("state", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###
