from alembic import op

revision = "bc5de40a50f4"
down_revision = "1af8ebb4c60e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("category", "is_locked")
    op.drop_column("category", "in_header")
    # ### end Alembic commands ###
