import sqlalchemy as sa
from alembic import op

revision = "45e8648b9a5b"
down_revision = "80f2e6ecb5b4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flask_static",
        sa.Column("static_path", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "flask_blueprint", sa.Column("static_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None,
        "flask_blueprint",
        "flask_static",
        ["static_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("flask_blueprint", "static_path")
    op.add_column("flask_route", sa.Column("static_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "flask_route", "flask_static", ["static_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("flask_route", "static_path")
    # ### end Alembic commands ###
