from alembic import op
import sqlalchemy as sa


revision = '99fc19f678f2'
down_revision = '5a5308b4b68c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'billing', 'user', ['user_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key(None, 'shipping', 'user', ['user_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.add_column('user', sa.Column('allow_mass_email', sa.Boolean(), nullable=False, server_default="true"))
    # ### end Alembic commands ###
