from alembic import op

revision = "aed7d868cdcc"
down_revision = "99fc19f678f2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("email", "template_id", new_column_name="event_id")
    # ### end Alembic commands ###
