import sqlalchemy as sa
from alembic import op

revision = "3c7c24dd98a1"
down_revision = "4b17d67bafc1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "country",
        sa.Column(
            "state_required", sa.Boolean(), nullable=False, server_default="false"
        ),
    )
    # ### end Alembic commands ###
