from alembic import op

revision = "1af8ebb4c60e"
down_revision = "71cb27548a68"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("category_child_id_fkey", "category", type_="foreignkey")
    op.drop_column("category", "child_id")
    # ### end Alembic commands ###
