import sqlalchemy as sa
from alembic import op

revision = "80f2e6ecb5b4"
down_revision = "a8eece01592d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "flask_blueprint",
        "static_path",
        existing_type=sa.VARCHAR(length=128),
        nullable=True,
    )
    op.drop_constraint(
        "flask_blueprint_static_path_key", "flask_blueprint", type_="unique"
    )
    op.alter_column(
        "flask_route",
        "static_path",
        existing_type=sa.VARCHAR(length=128),
        nullable=True,
    )
    op.drop_constraint("flask_route_static_path_key", "flask_route", type_="unique")
    # ### end Alembic commands ###
