import sqlalchemy as sa
from alembic import op

revision = "eb8d9926e200"
down_revision = "3c7c24dd98a1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flask_blueprint",
        sa.Column("attributes", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("endpoint", sa.String(length=64), nullable=False),
        sa.Column("in_sitemap", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("endpoint"),
    )
    op.rename_table("page", "flask_route")
    # ### end Alembic commands ###
