[tool.ruff]
lint.select = ["F", "E", "W", "I"]
lint.ignore = ["E501"]
line-length = 88
target-version = "py311"
cache-dir = ".cache/ruff"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.mypy]
check_untyped_defs=true
ignore_missing_imports=true
cache_dir=".cache/mypy"

[tool.djlint]
profile="jinja"
quiet=true
use_gitignore=true
max_line_length=100
preserve_blank_lines=true
format_js=true
format_css = true

[tool.djlint.js]
indent_size = 2
indent_char = " "
max_preserve_newlines = 1
preserve_newlines = true
wrap_line_length = 100
end_with_newline = true
brace_style = "collapse,preserve-inline"
extra_liners = []
keep_array_indentation = false
break_chained_methods = false
indent_scripts = "normal"
space_before_conditional = true
unescape_strings = false
jslint_happy = false
comma_first = false
e4x = false
indent_empty_lines = false

[tool.djlint.css]
indent = "  "
openbrace = "end-of-line"
autosemicolon = true
newline_between_rules = true

[tool.pytest.ini_options]
python_files="test_*.py"
addopts="--maxfail=1"
faulthandler_timeout=5
cache_dir=".cache/pytest"
