[tool.ruff]
select = ["F", "E", "W", "I"]
line-length = 88
cache-dir = "~/.cache/ruff"
target-version = "py311"
ignore = ["E501"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.black]
line-length = 88
target-version = ['py311']

[tool.djlint]
blank_line_before_tag="extends,block"
custom_blocks="pack"
line_break_after_multiline_tag=true
max_attribute_length=10
max_line_length=100
profile="jinja"
quiet=true
use_gitignore=true

[tool.pytest.ini_options]
addopts="--maxfail=1"
cache_dir="~/.cache/pytest"
faulthandler_timeout=5
python_files="test_*.py"
filterwarnings="ignore::DeprecationWarning:pycountry"