[tool.ruff]
select = ["F", "E", "W", "I"]
line-length = 88
target-version = "py311"
cache-dir = ".cache/ruff"

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.black]
line-length = 88
target-version = ['py311']

[tool.djlint]
profile="jinja"
quiet=true
use_gitignore=true
max_attribute_length=10
max_line_length=100
custom_blocks="pack"
blank_line_before_tag="extends,block"
line_break_after_multiline_tag=true

[tool.pytest.ini_options]
python_files="test_*.py"
addopts="--maxfail=1"
faulthandler_timeout=5
filterwarnings="ignore::DeprecationWarning:pycountry"
cache_dir=".cache/pytest"

[tool.mypy]
ignore_missing_imports=true
exclude="web/(config|database)/*"
cache_dir=".cache/mypy"

[[tool.mypy.overrides]]
module = "web.config.*"
follow_imports="skip"

[[tool.mypy.overrides]]
module = "web.database.*"
follow_imports="skip"