from alembic import op

revision = "99ca8d0374be"
down_revision = "c34da6d33e62"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("category_child_id_fkey", "category", type_="foreignkey")
    op.drop_column("category", "child_id")
    # ### end Alembic commands ###
