from alembic import op

revision = "8319dd0e7905"
down_revision = "d5b84d2d05cb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("route", "flask_route")
    op.rename_table("blueprint", "flask_blueprint")
    # ### end Alembic commands ###
