from alembic import op

revision = "0cb8f3e0b0aa"
down_revision = "239b482556fb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("shipment_url_order_id_key", "shipment", type_="unique")
    # ### end Alembic commands ###
