import sqlalchemy as sa
from alembic import op

revision = "9915034938ed"
down_revision = "e8e2ef759229"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_route",
        sa.Column(
            "is_collection", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###
