from alembic import op

revision = "c70e06b45edb"
down_revision = "423ebcd85503"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("order_currency_id_fkey", "order", type_="foreignkey")
    op.drop_column("order", "currency_id")
    # ### end Alembic commands ###
