import sqlalchemy as sa
from alembic import op

revision = "17ad037266d8"
down_revision = "754f76c63363"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flask_blueprint", sa.Column("css_path", sa.String(length=128), nullable=True)
    )
    op.add_column(
        "flask_blueprint", sa.Column("js_path", sa.String(length=128), nullable=True)
    )
    op.drop_constraint(
        "flask_blueprint_static_id_fkey", "flask_blueprint", type_="foreignkey"
    )
    op.drop_column("flask_blueprint", "static_id")
    op.add_column(
        "flask_route", sa.Column("css_path", sa.String(length=128), nullable=True)
    )
    op.add_column(
        "flask_route", sa.Column("js_path", sa.String(length=128), nullable=True)
    )
    op.drop_constraint("flask_route_static_id_fkey", "flask_route", type_="foreignkey")
    op.drop_column("flask_route", "static_id")
    op.add_column(
        "setting", sa.Column("css_path", sa.String(length=128), nullable=True)
    )
    op.add_column("setting", sa.Column("js_path", sa.String(length=128), nullable=True))
    op.drop_table("flask_static")
    # ### end Alembic commands ###
