import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "002457ecabd0"
down_revision = "d8912816ad82"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "email",
        "data",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::json"),  # type: ignore[arg-type]
        server_default=sa.text("'{}'::jsonb"),
    )
    # ### end Alembic commands ###
