from alembic import op
import sqlalchemy as sa


revision = 'a0707f5166bd'
down_revision = '99ca8d0374be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'in_header')
    op.drop_column('category', 'is_locked')
    # ### end Alembic commands ###
