import sqlalchemy as sa
from alembic import op

revision = "bb2aec997183"
down_revision = "8319dd0e7905"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flask_blueprint",
        sa.Column("static_path", sa.String(length=128), nullable=False),
    )
    op.create_unique_constraint(None, "flask_blueprint", ["static_path"])
    op.add_column(
        "flask_route", sa.Column("static_path", sa.String(length=128), nullable=False)
    )
    op.create_unique_constraint(None, "flask_route", ["static_path"])
    # ### end Alembic commands ###
