from alembic import op

revision = "f48222604194"
down_revision = "ac428a5f2656"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "allow_mass_email", new_column_name="bulk_email")
    # ### end Alembic commands ###
