import sqlalchemy as sa
from alembic import op

revision = "24e57953ff0f"
down_revision = "c70e06b45edb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "country",
        sa.Column("vat_required", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###
