import sqlalchemy as sa
from alembic import op

revision = "93d8c99a8e6c"
down_revision = "4a5b6c3e7cd6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "country",
        sa.Column(
            "state_required", sa.Boolean(), nullable=False, server_default="false"
        ),
    )
    # ### end Alembic commands ###
