import sqlalchemy as sa
from alembic import op

revision = "feb89f369182"
down_revision = "54c0a4af50d1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sku", sa.Column("stock", sa.Integer(), nullable=False, server_default="1")
    )
    # ### end Alembic commands ###
