from alembic import op

revision = "54c0a4af50d1"
down_revision = "3c7493c28b01"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "sku", ["number"])
    # ### end Alembic commands ###
