import sqlalchemy as sa
from alembic import op

revision = "4a5b6c3e7cd6"
down_revision = "a0707f5166bd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("billing", sa.Column("state", sa.String(length=64), nullable=True))
    op.add_column("shipping", sa.Column("state", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###
