from alembic import op

revision = "5edc993b57b9"
down_revision = "2567963776f5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("email", "template_id", new_column_name="event_id")
    # ### end Alembic commands ###
