from alembic import op

revision = "c34da6d33e62"
down_revision = "28d14049162a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "billing", "user", ["user_id"], ["id"], ondelete="CASCADE", use_alter=True
    )
    op.create_foreign_key(
        None,
        "shipping",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
        use_alter=True,
    )
    # ### end Alembic commands ###
