import sqlalchemy as sa
from alembic import op

revision = "ac428a5f2656"
down_revision = "67c7c76dc043"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email",
        sa.Column("status_id", sa.Integer(), server_default="1", nullable=False),
    )
    op.drop_constraint("email_user_id_fkey", "email", type_="foreignkey")
    op.create_foreign_key(
        None, "email", "email_status", ["status_id"], ["id"], ondelete="RESTRICT"
    )
    op.create_foreign_key(
        None, "email", "user", ["user_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###
