import sqlalchemy as sa
from alembic import op

revision = "3c7493c28b01"
down_revision = "5edc993b57b9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shipment", sa.Column("carrier", sa.String(length=64), nullable=True))
    op.add_column("shipment", sa.Column("code", sa.String(length=64), nullable=True))
    op.add_column("sku", sa.Column("number", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###
