from alembic import op

revision = "c9ae038ccc5c"
down_revision = "15363422fcf3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("billing_user_id_fkey", "billing", type_="foreignkey")
    op.create_foreign_key(
        None, "billing", "user", ["user_id"], ["id"], ondelete="CASCADE", use_alter=True
    )
    # ### end Alembic commands ###
