import sqlalchemy as sa
from alembic import op

revision = "15363422fcf3"
down_revision = "61f2ba171bcc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("api_key", sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, "user", ["api_key"])
    # ### end Alembic commands ###
