import sqlalchemy as sa
from alembic import op

revision = "00ad8e394454"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "article",
        sa.Column("html", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("summary", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "category",
        sa.Column("in_header", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("child_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["child_id"], ["category.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "coupon",
        sa.Column(
            "amount", sa.Numeric(precision=10, scale=4, asdecimal=False), nullable=True
        ),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "rate", sa.Numeric(precision=10, scale=4, asdecimal=False), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("amount IS NULL OR rate IS NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "currency",
        sa.Column("code", sa.String(length=3), nullable=False),
        sa.Column(
            "rate", sa.Numeric(precision=10, scale=4, asdecimal=False), nullable=False
        ),
        sa.Column("symbol", sa.String(length=3), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "file_type",
        sa.Column("name", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "invoice",
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("number", sa.String(length=16), nullable=False),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("number"),
    )
    op.create_table(
        "language",
        sa.Column("code", sa.String(length=2), nullable=False),
        sa.Column("in_sitemap", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "order_status",
        sa.Column("name", sa.String(length=16), nullable=False),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "page",
        sa.Column("desc", sa.String(length=256), nullable=True),
        sa.Column("endpoint", sa.String(length=64), nullable=False),
        sa.Column("in_sitemap", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("robots", sa.String(length=256), nullable=False),
        sa.Column("img_url", sa.String(length=256), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("endpoint"),
    )
    op.create_table(
        "product_link_type",
        sa.Column("name", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "product_type",
        sa.Column("name", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "redirect",
        sa.Column("url_from", sa.String(length=256), nullable=False),
        sa.Column("url_to", sa.String(length=256), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url_from"),
    )
    op.create_table(
        "region",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "shipment_class",
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_role",
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "country",
        sa.Column("code", sa.String(length=2), nullable=False),
        sa.Column("in_sitemap", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("currency_id", sa.Integer(), nullable=False),
        sa.Column("region_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["currency_id"], ["currency.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["region_id"], ["region.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "file",
        sa.Column("desc", sa.String(length=64), nullable=True),
        sa.Column("path", sa.String(length=256), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["type_id"], ["file_type.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path"),
    )
    op.create_table(
        "product",
        sa.Column("file_url", sa.String(length=128), nullable=True),
        sa.Column("html", sa.Text(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("read_html", sa.Boolean(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("summary", sa.String(length=64), nullable=True),
        sa.Column(
            "unit_price",
            sa.Numeric(precision=10, scale=4, asdecimal=False),
            nullable=False,
        ),
        sa.Column("shipment_class_id", sa.Integer(), nullable=True),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["shipment_class_id"], ["shipment_class.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["type_id"], ["product_type.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "article_media",
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["article_id"], ["article.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["file_id"], ["file.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("article_id", "file_id"),
    )
    op.create_table(
        "billing",
        sa.Column("address", sa.String(length=64), nullable=False),
        sa.Column("city", sa.String(length=64), nullable=False),
        sa.Column("company", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=64), nullable=False),
        sa.Column("first_name", sa.String(length=64), nullable=False),
        sa.Column("last_name", sa.String(length=64), nullable=False),
        sa.Column("phone", sa.String(length=64), nullable=True),
        sa.Column("vat", sa.String(length=64), nullable=True),
        sa.Column("zip_code", sa.String(length=64), nullable=False),
        sa.Column("country_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["country_id"], ["country.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_media",
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["file_id"], ["file.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_id", "product_id"),
    )
    op.create_table(
        "product_option",
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id", "slug"),
    )
    op.create_table(
        "shipment_zone",
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("country_id", sa.Integer(), nullable=True),
        sa.Column("region_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("country_id IS NULL OR region_id IS NULL"),
        sa.ForeignKeyConstraint(["country_id"], ["country.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["region_id"], ["region.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shipping",
        sa.Column("address", sa.String(length=64), nullable=False),
        sa.Column("city", sa.String(length=64), nullable=False),
        sa.Column("company", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=64), nullable=False),
        sa.Column("first_name", sa.String(length=64), nullable=False),
        sa.Column("last_name", sa.String(length=64), nullable=False),
        sa.Column("phone", sa.String(length=64), nullable=True),
        sa.Column("zip_code", sa.String(length=64), nullable=False),
        sa.Column("country_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["country_id"], ["country.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sku",
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column(
            "unit_price",
            sa.Numeric(precision=10, scale=4, asdecimal=False),
            nullable=False,
        ),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("unit_price >= 0"),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "category_item",
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("article_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("sku_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("sku_id IS NULL OR article_id IS NULL"),
        sa.ForeignKeyConstraint(["article_id"], ["article.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["category_id"], ["category.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sku_id"], ["sku.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("category_id", "article_id"),
        sa.UniqueConstraint("category_id", "sku_id"),
    )
    op.create_table(
        "product_link",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("sku_id", sa.Integer(), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sku_id"], ["sku.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["type_id"], ["product_link_type.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id", "sku_id", "type_id"),
    )
    op.create_table(
        "product_value",
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column(
            "unit_price",
            sa.Numeric(precision=10, scale=4, asdecimal=False),
            nullable=False,
        ),
        sa.Column("media_id", sa.Integer(), nullable=True),
        sa.Column("option_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("unit_price >= 0"),
        sa.ForeignKeyConstraint(
            ["media_id"], ["product_media.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["option_id"], ["product_option.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("option_id", "slug"),
    )
    op.create_table(
        "shipment_method",
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("phone_required", sa.Boolean(), nullable=False),
        sa.Column(
            "unit_price",
            sa.Numeric(precision=10, scale=4, asdecimal=False),
            nullable=False,
        ),
        sa.Column("class_id", sa.Integer(), nullable=False),
        sa.Column("zone_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("unit_price >= 0"),
        sa.ForeignKeyConstraint(
            ["class_id"], ["shipment_class.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["zone_id"], ["shipment_zone.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("email", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=True),
        sa.Column("billing_id", sa.Integer(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("shipping_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["billing_id"], ["billing.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["role_id"], ["user_role.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["shipping_id"], ["shipping.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "access",
        sa.Column("session_key", sa.String(length=64), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("session_key IS NULL OR user_id IS NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_key"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "sku_detail",
        sa.Column("option_id", sa.Integer(), nullable=False),
        sa.Column("sku_id", sa.Integer(), nullable=False),
        sa.Column("value_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["option_id"], ["product_option.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["sku_id"], ["sku.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["value_id"], ["product_value.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sku_id", "value_id"),
    )
    op.create_table(
        "verification",
        sa.Column("key", sa.String(length=256), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cart",
        sa.Column(
            "shipment_price",
            sa.Numeric(precision=10, scale=4, asdecimal=False),
            nullable=False,
        ),
        sa.Column(
            "vat_rate",
            sa.Numeric(precision=4, scale=2, asdecimal=False),
            nullable=False,
        ),
        sa.Column("vat_reverse", sa.Boolean(), nullable=False),
        sa.Column("access_id", sa.Integer(), nullable=False),
        sa.Column("billing_id", sa.Integer(), nullable=True),
        sa.Column("coupon_id", sa.Integer(), nullable=True),
        sa.Column("currency_id", sa.Integer(), nullable=False),
        sa.Column("shipment_method_id", sa.Integer(), nullable=True),
        sa.Column("shipping_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("shipment_price >= 0"),
        sa.CheckConstraint("vat_rate >= 1"),
        sa.ForeignKeyConstraint(["access_id"], ["access.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["billing_id"], ["billing.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["coupon_id"], ["coupon.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["currency_id"], ["currency.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["shipment_method_id"], ["shipment_method.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["shipping_id"], ["shipping.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("access_id"),
    )
    op.create_table(
        "order",
        sa.Column(
            "coupon_amount",
            sa.Numeric(precision=10, scale=4, asdecimal=False),
            nullable=True,
        ),
        sa.Column("coupon_code", sa.String(length=16), nullable=True),
        sa.Column(
            "coupon_rate",
            sa.Numeric(precision=10, scale=4, asdecimal=False),
            nullable=True,
        ),
        sa.Column("mollie_id", sa.String(length=64), nullable=True),
        sa.Column("shipment_name", sa.String(length=64), nullable=True),
        sa.Column(
            "shipment_price",
            sa.Numeric(precision=10, scale=4, asdecimal=False),
            nullable=False,
        ),
        sa.Column(
            "total_price",
            sa.Numeric(precision=10, scale=4, asdecimal=False),
            nullable=False,
        ),
        sa.Column(
            "vat_rate",
            sa.Numeric(precision=4, scale=2, asdecimal=False),
            nullable=False,
        ),
        sa.Column("vat_reverse", sa.Boolean(), nullable=False),
        sa.Column("access_id", sa.Integer(), nullable=False),
        sa.Column("billing_id", sa.Integer(), nullable=True),
        sa.Column("currency_id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=True),
        sa.Column("shipping_id", sa.Integer(), nullable=True),
        sa.Column("status_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("coupon_amount IS NULL OR coupon_rate IS NULL"),
        sa.CheckConstraint("shipment_price >= 0"),
        sa.CheckConstraint("total_price >= 0"),
        sa.CheckConstraint("vat_rate >= 1"),
        sa.ForeignKeyConstraint(["access_id"], ["access.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["billing_id"], ["billing.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["currency_id"], ["currency.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoice.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["shipping_id"], ["shipping.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["status_id"], ["order_status.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mollie_id"),
    )
    op.create_table(
        "cart_item",
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("cart_id", sa.Integer(), nullable=False),
        sa.Column("sku_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("quantity >= 1"),
        sa.ForeignKeyConstraint(["cart_id"], ["cart.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sku_id"], ["sku.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cart_id", "sku_id"),
    )
    op.create_table(
        "order_line",
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "total_price",
            sa.Numeric(precision=10, scale=4, asdecimal=False),
            nullable=False,
        ),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("sku_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("quantity >= 1"),
        sa.CheckConstraint("total_price >= 0"),
        sa.ForeignKeyConstraint(["order_id"], ["order.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sku_id"], ["sku.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id", "sku_id"),
    )
    op.create_table(
        "refund",
        sa.Column("mollie_id", sa.String(length=64), nullable=True),
        sa.Column("number", sa.String(length=16), nullable=False),
        sa.Column(
            "total_price",
            sa.Numeric(precision=10, scale=4, asdecimal=False),
            nullable=False,
        ),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("total_price < 0"),
        sa.ForeignKeyConstraint(["order_id"], ["order.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mollie_id"),
        sa.UniqueConstraint("number"),
    )
    op.create_table(
        "shipment",
        sa.Column("url", sa.String(length=256), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["order_id"], ["order.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url", "order_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shipment")
    op.drop_table("refund")
    op.drop_table("order_line")
    op.drop_table("cart_item")
    op.drop_table("order")
    op.drop_table("cart")
    op.drop_table("verification")
    op.drop_table("sku_detail")
    op.drop_table("access")
    op.drop_table("user")
    op.drop_table("shipment_method")
    op.drop_table("product_value")
    op.drop_table("product_link")
    op.drop_table("category_item")
    op.drop_table("sku")
    op.drop_table("shipping")
    op.drop_table("shipment_zone")
    op.drop_table("product_option")
    op.drop_table("product_media")
    op.drop_table("billing")
    op.drop_table("article_media")
    op.drop_table("product")
    op.drop_table("file")
    op.drop_table("country")
    op.drop_table("user_role")
    op.drop_table("shipment_class")
    op.drop_table("region")
    op.drop_table("redirect")
    op.drop_table("product_type")
    op.drop_table("product_link_type")
    op.drop_table("page")
    op.drop_table("order_status")
    op.drop_table("language")
    op.drop_table("invoice")
    op.drop_table("file_type")
    op.drop_table("currency")
    op.drop_table("coupon")
    op.drop_table("category")
    op.drop_table("article")
    # ### end Alembic commands ###
