from alembic import op

revision = "cfc0ded393e9"
down_revision = "c9ae038ccc5c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("shipping_user_id_fkey", "shipping", type_="foreignkey")
    op.create_foreign_key(
        None,
        "shipping",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
        use_alter=True,
    )
    # ### end Alembic commands ###
