import sqlalchemy as sa
from alembic import op

revision = "61f2ba171bcc"
down_revision = "028e32355247"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("billing", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None,
        "billing",
        "user",
        ["user_id"],
        ["id"],
        ondelete="RESTRICT",
        use_alter=True,
    )
    op.add_column("shipping", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None,
        "shipping",
        "user",
        ["user_id"],
        ["id"],
        ondelete="RESTRICT",
        use_alter=True,
    )
    # ### end Alembic commands ###
