import sqlalchemy as sa
from alembic import op

revision = "0d119c697c0f"
down_revision = "4d5f48ddc1f9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "newsletter_email", sa.Boolean(), server_default="true", nullable=False
        ),
    )
    # ### end Alembic commands ###
