import sqlalchemy as sa
from alembic import op

revision = "e51d3b36a9f0"
down_revision = "43a85302c5a9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cart",
        "shipment_price",
        existing_type=sa.NUMERIC(precision=10, scale=4),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=False,
        existing_server_default="'0'::numeric",
    )
    op.alter_column(
        "coupon",
        "amount",
        existing_type=sa.NUMERIC(precision=10, scale=4),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "order",
        "coupon_amount",
        existing_type=sa.NUMERIC(precision=10, scale=4),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "order",
        "shipment_price",
        existing_type=sa.NUMERIC(precision=10, scale=4),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "order",
        "total_price",
        existing_type=sa.NUMERIC(precision=10, scale=4),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "order_line",
        "total_price",
        existing_type=sa.NUMERIC(precision=10, scale=4),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "product",
        "unit_price",
        existing_type=sa.NUMERIC(precision=10, scale=4),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "product_value",
        "unit_price",
        existing_type=sa.NUMERIC(precision=10, scale=4),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=False,
        existing_server_default="'0'::numeric",
    )
    op.alter_column(
        "refund",
        "total_price",
        existing_type=sa.NUMERIC(precision=10, scale=4),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "shipment_method",
        "unit_price",
        existing_type=sa.NUMERIC(precision=10, scale=4),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=False,
        existing_server_default="'0'::numeric",
    )
    op.alter_column(
        "sku",
        "unit_price",
        existing_type=sa.NUMERIC(precision=10, scale=4),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
