import sqlalchemy as sa
from alembic import op

revision = "f0d24417be87"
down_revision = "0d119c697c0f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("display_name", sa.String(length=128), nullable=True)
    )
    # ### end Alembic commands ###
