import sqlalchemy as sa
from alembic import op

revision = "bdb48533ca09"
down_revision = "e51d3b36a9f0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cart",
        "vat_rate",
        existing_type=sa.NUMERIC(precision=4, scale=2),
        type_=sa.Numeric(precision=4, scale=3),
        existing_nullable=False,
        existing_server_default="'1'::numeric",
    )
    op.alter_column(
        "order",
        "vat_rate",
        existing_type=sa.NUMERIC(precision=4, scale=2),
        type_=sa.Numeric(precision=4, scale=3),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
