import sqlalchemy as sa
from alembic import op

revision = "577c6a34b207"
down_revision = "b2d9202ed307"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cart",
        "vat_rate",
        existing_type=sa.NUMERIC(precision=4, scale=3),
        server_default="1",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
