from alembic import op

revision = "4d5f48ddc1f9"
down_revision = "b8c17252bac6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("country", "is_active", new_column_name="allows_shipping")
    op.alter_column("country", "vat_required", new_column_name="requires_billing_vat")
    op.alter_column(
        "country", "state_required", new_column_name="requires_billing_state"
    )
    op.alter_column(
        "shipment_method", "phone_required", new_column_name="requires_billing_phone"
    )
    # ### end Alembic commands ###
