import sqlalchemy as sa
from alembic import op

revision = "530de05345bf"
down_revision = "bdb48533ca09"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "coupon",
        "rate",
        existing_type=sa.NUMERIC(precision=10, scale=4),
        type_=sa.Numeric(precision=12, scale=6),
        existing_nullable=True,
    )
    op.alter_column(
        "currency",
        "rate",
        existing_type=sa.NUMERIC(precision=10, scale=4),
        type_=sa.Numeric(precision=12, scale=6),
        existing_nullable=False,
        existing_server_default="'1'::numeric",
    )
    op.alter_column(
        "order",
        "coupon_rate",
        existing_type=sa.NUMERIC(precision=10, scale=4),
        type_=sa.Numeric(precision=12, scale=6),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
