import sqlalchemy as sa
from alembic import op

revision = "b8c17252bac6"
down_revision = "20250715_185051"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "country",
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
    )
    # ### end Alembic commands ###
