import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "f6e38c399e7e"
down_revision = "f0d24417be87"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_route", sa.Column("sitemap_query_key", sa.String(length=32), nullable=True)
    )
    op.add_column(
        "app_route",
        sa.Column("sitemap_query_values", postgresql.ARRAY(sa.Text()), nullable=True),
    )
    op.alter_column(
        "user",
        "bulk_email",
        existing_type=sa.BOOLEAN(),
        server_default="false",
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "newsletter_email",
        existing_type=sa.BOOLEAN(),
        server_default="false",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
