import sqlalchemy as sa
from alembic import op

revision = "add0c6f4ccd6"
down_revision = "f6e38c399e7e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_route", sa.Column("breadcrumb_name", sa.String(length=64), nullable=True)
    )
    # ### end Alembic commands ###
