import sqlalchemy as sa
from alembic import op

revision = "88d1167e5edf"
down_revision = "cec083ca25eb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("category", sa.Column("route_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "category", "app_route", ["route_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###
