from alembic import op

revision = "4d18f0bcb4af"
down_revision = "12aaabd51c78"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "sku", ["number"])
    # ### end Alembic commands ###
