from alembic import op

revision = "849359155b37"
down_revision = "0de5df0c233c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("shipment_url_order_id_key", "shipment", type_="unique")
    # ### end Alembic commands ###
