import sqlalchemy as sa
from alembic import op

revision = "39988bd350c9"
down_revision = "849359155b37"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "article",
        "summary",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=256),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
