import sqlalchemy as sa
from alembic import op

revision = "d7625e55e31e"
down_revision = "88d1167e5edf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_route",
        sa.Column(
            "is_collection", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###
