import sqlalchemy as sa
from alembic import op

revision = "698253709d60"
down_revision = "70c51fa957eb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "billing",
        "address",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=128),
        existing_nullable=False,
    )
    op.add_column(
        "country",
        sa.Column("vat_required", sa.Boolean(), server_default="false", nullable=False),
    )
    op.alter_column(
        "shipping",
        "address",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=128),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
