from alembic import op

revision = "70c51fa957eb"
down_revision = "0d4f75bb3b63"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "billing", "user", ["user_id"], ["id"], ondelete="CASCADE", use_alter=True
    )
    op.create_foreign_key(
        None,
        "shipping",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
        use_alter=True,
    )
    # ### end Alembic commands ###
