import sqlalchemy as sa
from alembic import op

revision = "cec083ca25eb"
down_revision = "cdb3fe9b6bb2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("article", sa.Column("route_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "article", "app_route", ["route_id"], ["id"], ondelete="SET NULL"
    )
    op.add_column("sku", sa.Column("route_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "sku", "app_route", ["route_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###
