import sqlalchemy as sa
from alembic import op

revision = "0a46f4e0dce9"
down_revision = "4d18f0bcb4af"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sku", sa.Column("stock", sa.Integer(), nullable=False))
    # ### end Alembic commands ###
