name: Linter

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - run: |
          pip install --upgrade pip
          pip install -r requirements-dev.txt
      - run: |
          pycodestyle .
          black . --check --quiet --diff --color