name: Release

on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get version number
        run: |
          echo "VERSION=$(echo "__version__ = "1.9.8"" | sed 's/[^0-9\.]*//g')" >> $GITHUB_ENV
          echo ${{ env.VERSION }}