name: Release

on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get version number
        run: |
          echo "VERSION=1.9.8" >> $GITHUB_ENV
          echo "${{ env.VERSION }}"