name: Tester

on: [ push, pull_request ]

env:
  APP_DEBUG: ${{ vars.APP_DEBUG }}
  APP_SECRET: ${{ vars.APP_SECRET }}
  CDN_HOSTNAME: ${{ vars.CDN_HOSTNAME }}
  CDN_PASSWORD: ${{ secrets.CDN_PASSWORD }}
  CDN_URL: ${{ vars.CDN_URL }}
  CDN_USERNAME: ${{ vars.CDN_USERNAME }}
  CDN_ZONE: ${{ vars.CDN_ZONE }}
  CONFIG_PATH: ${{ vars.CONFIG_PATH }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  EMAIL_METHOD: ${{ vars.EMAIL_METHOD }}
  EMAIL_FROM: ${{ vars.EMAIL_FROM }}
  EMAIL_TO: ${{ vars.EMAIL_TO }}
  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
  GOOGLE_PLACE_ID: ${{ vars.GOOGLE_PLACE_ID }}
  LOCALHOST: ${{ vars.LOCALHOST }}
  MOLLIE_KEY: ${{ secrets.MOLLIE_KEY }}
  SEED_EXTERNAL: ${{ vars.SEED_EXTERNAL }}
  SMTP_HOST: ${{ vars.SMTP_HOST }}
  SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
  SMTP_PORT: ${{ vars.SMTP_PORT }}
  SMTP_USERNAME: ${{ vars.SMTP_USERNAME }}

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Test with pytest
        run: |
          pytest -s .