name: Workflow
on: [push, pull_request]
permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: make packages
      - name: Run linters
        run: make lint
  
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create bundle
        run: |
          TIMESTAMP=$(date +%Y%m%d)
          mkdir -p bundles
          git bundle create "bundles/${TIMESTAMP} ${{ github.event.repository.name }}.bundle" --all
          sha256sum "bundles/${TIMESTAMP} ${{ github.event.repository.name }}.bundle" > "bundles/${TIMESTAMP} ${{ github.event.repository.name }}.sha256"
      - name: Upload bundle via plain FTP (curl)
        env:
          FTP_HOSTNAME: ${{ secrets.FTP_HOSTNAME }}   # storage.bunnycdn.com
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}   # Storage Zone name
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          set -euo pipefail
          TIMESTAMP=$(date +%Y%m%d)

          for f in bundles/*; do
            base=$(basename "$f")
            remote_name=${base// /%20}
            curl --ftp-pasv \
                 --connect-timeout 30 --max-time 1800 \
                 --retry 6 --retry-delay 10 --retry-max-time 0 \
                 --user "${FTP_USERNAME}:${FTP_PASSWORD}" \
                 --ftp-create-dirs \
                 -T "$f" "ftp://${FTP_HOSTNAME}:21/backups/$remote_name"
          done

          echo "Listing /backups over plain FTP:"
          curl --ftp-pasv \
               --user "${FTP_USERNAME}:${FTP_PASSWORD}" \
               "ftp://${FTP_HOSTNAME}:21/backups/" -l

  # test:
  #   runs-on: ubuntu-latest
  #   needs: lint
  #   env:
  #     CONFIG_MODULE: "test.config"
  #   strategy:
  #     matrix:
  #       python-version: ["3.12"]
  #   services:
  #     postgres:
  #       image: postgres:15
  #       env:
  #         POSTGRES_PASSWORD: postgres
  #         POSTGRES_USER: postgres
  #         POSTGRES_DB: web_test
  #       options: >-
  #         --health-cmd pg_isready
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5
  #       ports:
  #         - 5432:5432
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #         cache: "pip"
  #     - name: Install dependencies
  #       run: pip install -r requirements.txt -r requirements-dev.txt
  #     - name: Run database migrations
  #       run: alembic upgrade head
  #     - name: Run unit tests
  #       run: |
  #         pytest . \
  #           --cov=pytest_cov \
  #           --cov-report=xml:.cache/pytest/coverage.xml \
  #           --junitxml=.cache/pytest/results.xml \
  #           --verbose --tb=short --durations=10
  #     - name: Upload test results
  #       uses: actions/upload-artifact@v4
  #       if: always()
  #       with:
  #         name: test-results-${{ matrix.python-version }}
  #         path: .cache/pytest/results.xml
  #         retention-days: 30
  #     - name: Upload coverage report
  #       uses: actions/upload-artifact@v4
  #       if: always()
  #       with:
  #         name: coverage-${{ matrix.python-version }}
  #         path: .cache/pytest/coverage.xml
  #         retention-days: 30
