name: Workflow
on: [push, pull_request]
permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: make packages
      - name: Run linters
        run: make lint
  
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Archive repository
        run: |
          sudo apt-get update
          sudo apt-get install zip
          zip -r archive.zip *
      - name: Upload archive
        uses: nerdoza/action-simple-file-upload@v2
        with:
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          host: ${{ secrets.FTP_HOSTNAME }}
          src: archive.zip
          dest: /archive.zip

  # test:
  #   runs-on: ubuntu-latest
  #   needs: lint
  #   env:
  #     CONFIG_MODULE: "test.config"
  #   strategy:
  #     matrix:
  #       python-version: ["3.12"]
  #   services:
  #     postgres:
  #       image: postgres:15
  #       env:
  #         POSTGRES_PASSWORD: postgres
  #         POSTGRES_USER: postgres
  #         POSTGRES_DB: web_test
  #       options: >-
  #         --health-cmd pg_isready
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5
  #       ports:
  #         - 5432:5432
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #         cache: "pip"
  #     - name: Install dependencies
  #       run: pip install -r requirements.txt -r requirements-dev.txt
  #     - name: Run database migrations
  #       run: alembic upgrade head
  #     - name: Run unit tests
  #       run: |
  #         pytest . \
  #           --cov=pytest_cov \
  #           --cov-report=xml:.cache/pytest/coverage.xml \
  #           --junitxml=.cache/pytest/results.xml \
  #           --verbose --tb=short --durations=10
  #     - name: Upload test results
  #       uses: actions/upload-artifact@v4
  #       if: always()
  #       with:
  #         name: test-results-${{ matrix.python-version }}
  #         path: .cache/pytest/results.xml
  #         retention-days: 30
  #     - name: Upload coverage report
  #       uses: actions/upload-artifact@v4
  #       if: always()
  #       with:
  #         name: coverage-${{ matrix.python-version }}
  #         path: .cache/pytest/coverage.xml
  #         retention-days: 30
