name: Workflow
on: [push, pull_request]
permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: make packages
      - name: Run linters
        run: make lint

  backup:
    runs-on: ubuntu-latest
    needs: lint
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Bypass triggers
        run: |
          echo "set man-db/auto-update false" | sudo debconf-communicate
          sudo dpkg-reconfigure man-db
      - name: Create bundle
        run: |
          TIMESTAMP=$(date +%Y%m%d)
          mkdir -p bundles
          git bundle create "bundles/${TIMESTAMP}_${{ github.event.repository.name }}.bundle" --all
      - name: Upload via lftp
        run: |
          sudo apt-get update && sudo apt-get install -y lftp
          for f in bundles/*; do
            [ -f "$f" ] || { echo "No bundle files found"; exit 1; }
            base=$(basename "$f")
            echo "Uploading $f -> /backups/$base"
            lftp -u "${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }}" ftp://${{ secrets.FTP_HOSTNAME }}:21 -e "set ftp:passive-mode true; set ftp:ssl-allow true; set ftp:ssl-force false; set ftp:ssl-auth TLS; set net:max-retries 2; set net:persist-retries 0; set net:timeout 20; set cmd:trace true; cd backups; put $f -o $base; bye"
          done

  # test:
  #   runs-on: ubuntu-latest
  #   needs: lint
  #   env:
  #     CONFIG_MODULE: "test.config"
  #   strategy:
  #     matrix:
  #       python-version: ["3.12"]
  #   services:
  #     postgres:
  #       image: postgres:15
  #       env:
  #         POSTGRES_PASSWORD: postgres
  #         POSTGRES_USER: postgres
  #         POSTGRES_DB: web_test
  #       options: >-
  #         --health-cmd pg_isready
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5
  #       ports:
  #         - 5432:5432
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #         cache: "pip"
  #     - name: Install dependencies
  #       run: pip install -r requirements.txt -r requirements-dev.txt
  #     - name: Run database migrations
  #       run: alembic upgrade head
  #     - name: Run unit tests
  #       run: |
  #         pytest . \
  #           --cov=pytest_cov \
  #           --cov-report=xml:.cache/pytest/coverage.xml \
  #           --junitxml=.cache/pytest/results.xml \
  #           --verbose --tb=short --durations=10
  #     - name: Upload test results
  #       uses: actions/upload-artifact@v4
  #       if: always()
  #       with:
  #         name: test-results-${{ matrix.python-version }}
  #         path: .cache/pytest/results.xml
  #         retention-days: 30
  #     - name: Upload coverage report
  #       uses: actions/upload-artifact@v4
  #       if: always()
  #       with:
  #         name: coverage-${{ matrix.python-version }}
  #         path: .cache/pytest/coverage.xml
  #         retention-days: 30
